{"name": "test_insert_pet", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/pet.json'", "trace": "def test_insert_pet():\n>       file = open(\"../data/pet.json\")\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/pet.json'\n\ntests\\test_pets.py:10: FileNotFoundError"}, "start": 1658400320365, "stop": 1658400320365, "uuid": "426010b7-36d3-45e7-9022-97fa1bb1ed54", "historyId": "220e8cae3a568b85121d0551a5ccb4aa", "testCaseId": "35c2937098d318b309b4c4340f19fdac", "fullName": "tests.test_pets#test_insert_pet", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_pets"}, {"name": "host", "value": "A00639991A"}, {"name": "thread", "value": "31176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_pets"}]}