{"name": "test_insert_pet", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/pet.json'", "trace": "def test_insert_pet():\n>       file = open(\"../data/pet.json\")\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/pet.json'\n\ntests\\test_pets.py:10: FileNotFoundError"}, "start": 1658400292594, "stop": 1658400292595, "uuid": "1527d786-8307-415c-b6fe-452d849f1590", "historyId": "220e8cae3a568b85121d0551a5ccb4aa", "testCaseId": "35c2937098d318b309b4c4340f19fdac", "fullName": "tests.test_pets#test_insert_pet", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_pets"}, {"name": "host", "value": "A00639991A"}, {"name": "thread", "value": "26088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_pets"}]}